version = 1

test_patterns = [
    "zc.recipe.egg_/src/zc/recipe/egg/tests.py",
    "src/zc/buildout/tests/**"
]

exclude_patterns = ["builds/**"]

[[analyzers]]
name = "python"
enabled = false

  [analyzers.meta]
  runtime_version = "3.x.x"
